{
 "title": "Hazelcast - \"@my.cluster1.name@\" cluster",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Python sentiment output",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hz_map_putCount{name=\"python_sentiment\"})",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "hz_map_putCount{name=\"python_sentiment\"}"
    }
   ]
  },
  {
   "title": "\"Put\" to maps",
   "type": "graph",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hz_map_putCount  " }
   ]
  },
  {
   "title": "Cluster size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hz_cluster_size" }
   ]
  }
 ]
}